-- ══════════════════════════════════════════════════════════════════════════
-- COMPLETE MASTER SUPABASE DATABASE SCHEMA FOR RKK NURSERY ACCOUNTING
-- Paste and Run this in Supabase: Dashboard -> SQL Editor -> New Query -> Run
-- ══════════════════════════════════════════════════════════════════════════

-- 1. App Cloud Settings Key-Value Store (Multi-user sync)
CREATE TABLE IF NOT EXISTS public.app_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Customers Table
CREATE TABLE IF NOT EXISTS public.ma_customers (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  org_id TEXT,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  city TEXT,
  state TEXT,
  pincode TEXT,
  zone TEXT,
  size_category TEXT,
  crop_types TEXT[],
  gstin TEXT,
  address TEXT,
  opening_balance NUMERIC DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Crops & Products Catalog
CREATE TABLE IF NOT EXISTS public.ma_products (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  code TEXT,
  crop_type TEXT,
  tray_size TEXT,
  variety_rates JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Sales Orders Table
CREATE TABLE IF NOT EXISTS public.ma_orders (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  order_no TEXT NOT NULL,
  customer_id TEXT,
  customer_name TEXT NOT NULL,
  order_date DATE NOT NULL,
  status TEXT DEFAULT 'confirmed',
  transport_charge NUMERIC DEFAULT 0,
  advance_payment NUMERIC DEFAULT 0,
  foc_amount NUMERIC DEFAULT 0,
  items_total NUMERIC DEFAULT 0,
  total_amount NUMERIC DEFAULT 0,
  paid_amount NUMERIC DEFAULT 0,
  due_amount NUMERIC DEFAULT 0,
  narration TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Sales Order Line Items
CREATE TABLE IF NOT EXISTS public.ma_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT REFERENCES public.ma_orders(id) ON DELETE CASCADE,
  product_name TEXT NOT NULL,
  variant_name TEXT,
  price NUMERIC DEFAULT 0,
  quantity NUMERIC DEFAULT 1,
  dispatch_from DATE,
  dispatch_to DATE,
  sowing_date DATE,
  dispatched_qty NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'pending'
);

-- 6. Vendor Purchase Bills Table
CREATE TABLE IF NOT EXISTS public.ma_purchase_bills (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  bill_no TEXT NOT NULL,
  party_id TEXT,
  party_name TEXT NOT NULL,
  bill_date DATE NOT NULL,
  gst_type TEXT DEFAULT 'percentage',
  gst_value NUMERIC DEFAULT 0,
  gst_amount NUMERIC DEFAULT 0,
  transport_charge NUMERIC DEFAULT 0,
  paid_amount NUMERIC DEFAULT 0,
  items_total NUMERIC DEFAULT 0,
  total_amount NUMERIC DEFAULT 0,
  due_amount NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'unpaid',
  narration TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Purchase Bill Line Items
CREATE TABLE IF NOT EXISTS public.ma_purchase_bill_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id TEXT REFERENCES public.ma_purchase_bills(id) ON DELETE CASCADE,
  product_name TEXT NOT NULL,
  variant_name TEXT,
  price NUMERIC DEFAULT 0,
  quantity NUMERIC DEFAULT 1,
  line_total NUMERIC DEFAULT 0
);

-- 8. Customer Payment Receipts Table
CREATE TABLE IF NOT EXISTS public.ma_receipts (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  receipt_no TEXT,
  order_id TEXT,
  customer_id TEXT,
  customer_name TEXT NOT NULL,
  receipt_date DATE NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  payment_mode TEXT DEFAULT 'Cash',
  reference_no TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Production Sowing Batches Table
CREATE TABLE IF NOT EXISTS public.ma_batches (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  batch_no TEXT NOT NULL,
  order_id TEXT,
  customer_id TEXT,
  customer_name TEXT,
  product_name TEXT NOT NULL,
  variant_name TEXT,
  tray_size TEXT,
  total_trays NUMERIC DEFAULT 0,
  total_seeds NUMERIC DEFAULT 0,
  sowing_date DATE NOT NULL,
  expected_germination_date DATE,
  ready_date DATE,
  status TEXT DEFAULT 'sown',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Dispatches Table
CREATE TABLE IF NOT EXISTS public.ma_dispatch (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  dispatch_no TEXT NOT NULL,
  dispatch_date DATE NOT NULL,
  order_id TEXT,
  customer_id TEXT,
  customer_name TEXT,
  driver_id TEXT,
  driver_name TEXT,
  vehicle_no TEXT,
  status TEXT DEFAULT 'scheduled',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Dispatch Line Items
CREATE TABLE IF NOT EXISTS public.ma_dispatch_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispatch_id TEXT REFERENCES public.ma_dispatch(id) ON DELETE CASCADE,
  product_name TEXT NOT NULL,
  variant_name TEXT,
  quantity NUMERIC DEFAULT 0
);

-- 12. Drivers Table
CREATE TABLE IF NOT EXISTS public.ma_drivers (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  phone TEXT,
  vehicle_no TEXT,
  license_no TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. Bank Accounts & Cash Master
CREATE TABLE IF NOT EXISTS public.ma_bank_accounts (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  account_name TEXT NOT NULL,
  account_number TEXT,
  ifsc_code TEXT,
  bank_name TEXT,
  account_type TEXT DEFAULT 'bank',
  opening_balance NUMERIC DEFAULT 0,
  current_balance NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. Bank Transactions & Adjustments
CREATE TABLE IF NOT EXISTS public.ma_bank_transactions (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  transaction_date DATE NOT NULL,
  type TEXT NOT NULL,
  adjust_type TEXT,
  from_account TEXT,
  to_account TEXT,
  amount NUMERIC NOT NULL DEFAULT 0,
  notes TEXT,
  ref_no TEXT,
  party_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. Operational Expenses Table
CREATE TABLE IF NOT EXISTS public.ma_expenses (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  expense_date DATE NOT NULL,
  category TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  paid_via TEXT DEFAULT 'Cash',
  paid_to TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 16. Audit Trail Logging Table
CREATE TABLE IF NOT EXISTS public.ma_audit_logs (
  id TEXT PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  user_email TEXT,
  user_role TEXT DEFAULT 'admin',
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  entity_label TEXT,
  action TEXT NOT NULL,
  changes_summary TEXT,
  previous_state JSONB,
  new_state JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 17. Atomic Order + Items Transaction Procedure
CREATE OR REPLACE FUNCTION atomic_create_order(
  p_order jsonb,
  p_items jsonb
) RETURNS jsonb AS $$
DECLARE
  v_order_id text;
  v_user_id uuid;
  v_item jsonb;
BEGIN
  v_user_id := auth.uid();
  v_order_id := COALESCE(p_order->>'id', 'ord-' || extract(epoch from now())::text);

  INSERT INTO ma_orders (
    id, user_id, order_no, customer_id, customer_name, order_date,
    status, transport_charge, advance_payment, foc_amount, items_total,
    total_amount, narration, created_at, updated_at
  ) VALUES (
    v_order_id, v_user_id, p_order->>'order_no', p_order->>'customer_id',
    p_order->>'customer_name', (p_order->>'order_date')::date,
    COALESCE(p_order->>'status', 'confirmed'),
    COALESCE((p_order->>'transport_charge')::numeric, 0),
    COALESCE((p_order->>'advance_payment')::numeric, 0),
    COALESCE((p_order->>'foc_amount')::numeric, 0),
    COALESCE((p_order->>'items_total')::numeric, 0),
    COALESCE((p_order->>'total_amount')::numeric, 0),
    p_order->>'narration', now(), now()
  )
  ON CONFLICT (id) DO UPDATE SET
    order_no = EXCLUDED.order_no,
    customer_id = EXCLUDED.customer_id,
    customer_name = EXCLUDED.customer_name,
    order_date = EXCLUDED.order_date,
    status = EXCLUDED.status,
    transport_charge = EXCLUDED.transport_charge,
    advance_payment = EXCLUDED.advance_payment,
    foc_amount = EXCLUDED.foc_amount,
    items_total = EXCLUDED.items_total,
    total_amount = EXCLUDED.total_amount,
    narration = EXCLUDED.narration,
    updated_at = now();

  DELETE FROM ma_order_items WHERE order_id = v_order_id;

  IF p_items IS NOT NULL AND jsonb_array_length(p_items) > 0 THEN
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
      INSERT INTO ma_order_items (
        order_id, product_name, variant_name, price, quantity,
        dispatch_from, dispatch_to, sowing_date, dispatched_qty, status
      ) VALUES (
        v_order_id, v_item->>'product_name', v_item->>'variant_name',
        COALESCE((v_item->>'price')::numeric, 0),
        COALESCE((v_item->>'quantity')::numeric, 1),
        v_item->>'dispatch_from', v_item->>'dispatch_to',
        v_item->>'sowing_date',
        COALESCE((v_item->>'dispatched_qty')::numeric, 0),
        COALESCE(v_item->>'status', 'pending')
      );
    END LOOP;
  END IF;

  RETURN jsonb_build_object('success', true, 'order_id', v_order_id);
EXCEPTION WHEN OTHERS THEN
  RAISE EXCEPTION 'Atomic order creation failed: %', SQLERRM;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 18. Atomic Purchase Bill + Items Transaction Procedure
CREATE OR REPLACE FUNCTION atomic_create_purchase_bill(
  p_bill jsonb,
  p_items jsonb
) RETURNS jsonb AS $$
DECLARE
  v_bill_id text;
  v_user_id uuid;
  v_item jsonb;
BEGIN
  v_user_id := auth.uid();
  v_bill_id := COALESCE(p_bill->>'id', 'pur-' || extract(epoch from now())::text);

  INSERT INTO ma_purchase_bills (
    id, user_id, bill_no, party_id, party_name, bill_date, gst_type,
    gst_value, gst_amount, transport_charge, paid_amount, items_total,
    total_amount, due_amount, status, narration, created_at
  ) VALUES (
    v_bill_id, v_user_id, p_bill->>'bill_no', p_bill->>'party_id',
    p_bill->>'party_name', (p_bill->>'bill_date')::date, p_bill->>'gst_type',
    COALESCE((p_bill->>'gst_value')::numeric, 0),
    COALESCE((p_bill->>'gst_amount')::numeric, 0),
    COALESCE((p_bill->>'transport_charge')::numeric, 0),
    COALESCE((p_bill->>'paid_amount')::numeric, 0),
    COALESCE((p_bill->>'items_total')::numeric, 0),
    COALESCE((p_bill->>'total_amount')::numeric, 0),
    COALESCE((p_bill->>'due_amount')::numeric, 0),
    COALESCE(p_bill->>'status', 'unpaid'), p_bill->>'narration', now()
  )
  ON CONFLICT (id) DO UPDATE SET
    bill_no = EXCLUDED.bill_no, party_id = EXCLUDED.party_id,
    party_name = EXCLUDED.party_name, bill_date = EXCLUDED.bill_date,
    gst_type = EXCLUDED.gst_type, gst_value = EXCLUDED.gst_value,
    gst_amount = EXCLUDED.gst_amount, transport_charge = EXCLUDED.transport_charge,
    paid_amount = EXCLUDED.paid_amount, items_total = EXCLUDED.items_total,
    total_amount = EXCLUDED.total_amount, due_amount = EXCLUDED.due_amount,
    status = EXCLUDED.status, narration = EXCLUDED.narration;

  DELETE FROM ma_purchase_bill_items WHERE bill_id = v_bill_id;

  IF p_items IS NOT NULL AND jsonb_array_length(p_items) > 0 THEN
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
      INSERT INTO ma_purchase_bill_items (
        bill_id, product_name, variant_name, price, quantity, line_total
      ) VALUES (
        v_bill_id, v_item->>'product_name', v_item->>'variant_name',
        COALESCE((v_item->>'price')::numeric, 0),
        COALESCE((v_item->>'quantity')::numeric, 1),
        COALESCE((v_item->>'price')::numeric, 0) * COALESCE((v_item->>'quantity')::numeric, 1)
      );
    END LOOP;
  END IF;

  RETURN jsonb_build_object('success', true, 'bill_id', v_bill_id);
EXCEPTION WHEN OTHERS THEN
  RAISE EXCEPTION 'Atomic purchase bill creation failed: %', SQLERRM;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 19. Enable Row-Level Security (RLS) on all 100% tables
ALTER TABLE public.ma_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_purchase_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_purchase_bill_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_dispatch ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_dispatch_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_bank_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ma_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- 20. Authenticated Access Policies for all tables
DO $$ 
DECLARE
  tbl text;
BEGIN
  FOR tbl IN 
    SELECT tablename FROM pg_tables 
    WHERE schemaname = 'public' 
      AND (tablename LIKE 'ma_%' OR tablename = 'app_settings')
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Authenticated users full access" ON %I;', tbl);
    EXECUTE format('CREATE POLICY "Authenticated users full access" ON %I FOR ALL TO authenticated USING (true) WITH CHECK (true);', tbl);
  END LOOP;
END $$;
